// Generated by jextract

package com.capstone4j.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union {
 *     aarch64_sysreg sysreg;
 *     aarch64_tlbi tlbi;
 *     aarch64_ic ic;
 *     int raw_val;
 * }
 * }
 */
public class aarch64_sysop_reg {

    aarch64_sysop_reg() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        capstone_h.C_INT.withName("sysreg"),
        capstone_h.C_INT.withName("tlbi"),
        capstone_h.C_INT.withName("ic"),
        capstone_h.C_INT.withName("raw_val")
    ).withName("$anon$1978:9");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt sysreg$LAYOUT = (OfInt)$LAYOUT.select(groupElement("sysreg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * aarch64_sysreg sysreg
     * }
     */
    public static final OfInt sysreg$layout() {
        return sysreg$LAYOUT;
    }

    private static final long sysreg$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * aarch64_sysreg sysreg
     * }
     */
    public static final long sysreg$offset() {
        return sysreg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * aarch64_sysreg sysreg
     * }
     */
    public static int sysreg(MemorySegment union) {
        return union.get(sysreg$LAYOUT, sysreg$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * aarch64_sysreg sysreg
     * }
     */
    public static void sysreg(MemorySegment union, int fieldValue) {
        union.set(sysreg$LAYOUT, sysreg$OFFSET, fieldValue);
    }

    private static final OfInt tlbi$LAYOUT = (OfInt)$LAYOUT.select(groupElement("tlbi"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * aarch64_tlbi tlbi
     * }
     */
    public static final OfInt tlbi$layout() {
        return tlbi$LAYOUT;
    }

    private static final long tlbi$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * aarch64_tlbi tlbi
     * }
     */
    public static final long tlbi$offset() {
        return tlbi$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * aarch64_tlbi tlbi
     * }
     */
    public static int tlbi(MemorySegment union) {
        return union.get(tlbi$LAYOUT, tlbi$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * aarch64_tlbi tlbi
     * }
     */
    public static void tlbi(MemorySegment union, int fieldValue) {
        union.set(tlbi$LAYOUT, tlbi$OFFSET, fieldValue);
    }

    private static final OfInt ic$LAYOUT = (OfInt)$LAYOUT.select(groupElement("ic"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * aarch64_ic ic
     * }
     */
    public static final OfInt ic$layout() {
        return ic$LAYOUT;
    }

    private static final long ic$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * aarch64_ic ic
     * }
     */
    public static final long ic$offset() {
        return ic$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * aarch64_ic ic
     * }
     */
    public static int ic(MemorySegment union) {
        return union.get(ic$LAYOUT, ic$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * aarch64_ic ic
     * }
     */
    public static void ic(MemorySegment union, int fieldValue) {
        union.set(ic$LAYOUT, ic$OFFSET, fieldValue);
    }

    private static final OfInt raw_val$LAYOUT = (OfInt)$LAYOUT.select(groupElement("raw_val"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static final OfInt raw_val$layout() {
        return raw_val$LAYOUT;
    }

    private static final long raw_val$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static final long raw_val$offset() {
        return raw_val$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static int raw_val(MemorySegment union) {
        return union.get(raw_val$LAYOUT, raw_val$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static void raw_val(MemorySegment union, int fieldValue) {
        union.set(raw_val$LAYOUT, raw_val$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

