// Generated by jextract

package com.capstone4j.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct cs_m68k_op_reg_pair {
 *     m68k_reg reg_0;
 *     m68k_reg reg_1;
 * }
 * }
 */
public class cs_m68k_op_reg_pair {

    cs_m68k_op_reg_pair() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        capstone_h.C_INT.withName("reg_0"),
        capstone_h.C_INT.withName("reg_1")
    ).withName("cs_m68k_op_reg_pair");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt reg_0$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reg_0"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * m68k_reg reg_0
     * }
     */
    public static final OfInt reg_0$layout() {
        return reg_0$LAYOUT;
    }

    private static final long reg_0$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * m68k_reg reg_0
     * }
     */
    public static final long reg_0$offset() {
        return reg_0$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * m68k_reg reg_0
     * }
     */
    public static int reg_0(MemorySegment struct) {
        return struct.get(reg_0$LAYOUT, reg_0$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * m68k_reg reg_0
     * }
     */
    public static void reg_0(MemorySegment struct, int fieldValue) {
        struct.set(reg_0$LAYOUT, reg_0$OFFSET, fieldValue);
    }

    private static final OfInt reg_1$LAYOUT = (OfInt)$LAYOUT.select(groupElement("reg_1"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * m68k_reg reg_1
     * }
     */
    public static final OfInt reg_1$layout() {
        return reg_1$LAYOUT;
    }

    private static final long reg_1$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * m68k_reg reg_1
     * }
     */
    public static final long reg_1$offset() {
        return reg_1$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * m68k_reg reg_1
     * }
     */
    public static int reg_1(MemorySegment struct) {
        return struct.get(reg_1$LAYOUT, reg_1$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * m68k_reg reg_1
     * }
     */
    public static void reg_1(MemorySegment struct, int fieldValue) {
        struct.set(reg_1$LAYOUT, reg_1$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

