// Generated by jextract

package com.suko.capstone4j.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * union {
 *     arm_sysreg mclasssysreg;
 *     arm_bankedreg bankedreg;
 *     int raw_val;
 * }
 * }
 */
public class arm_sysop_reg {

    arm_sysop_reg() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.unionLayout(
        capstone_h.C_INT.withName("mclasssysreg"),
        capstone_h.C_INT.withName("bankedreg"),
        capstone_h.C_INT.withName("raw_val")
    ).withName("$anon$415:9");

    /**
     * The layout of this union
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt mclasssysreg$LAYOUT = (OfInt)$LAYOUT.select(groupElement("mclasssysreg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * arm_sysreg mclasssysreg
     * }
     */
    public static final OfInt mclasssysreg$layout() {
        return mclasssysreg$LAYOUT;
    }

    private static final long mclasssysreg$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * arm_sysreg mclasssysreg
     * }
     */
    public static final long mclasssysreg$offset() {
        return mclasssysreg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * arm_sysreg mclasssysreg
     * }
     */
    public static int mclasssysreg(MemorySegment union) {
        return union.get(mclasssysreg$LAYOUT, mclasssysreg$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * arm_sysreg mclasssysreg
     * }
     */
    public static void mclasssysreg(MemorySegment union, int fieldValue) {
        union.set(mclasssysreg$LAYOUT, mclasssysreg$OFFSET, fieldValue);
    }

    private static final OfInt bankedreg$LAYOUT = (OfInt)$LAYOUT.select(groupElement("bankedreg"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * arm_bankedreg bankedreg
     * }
     */
    public static final OfInt bankedreg$layout() {
        return bankedreg$LAYOUT;
    }

    private static final long bankedreg$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * arm_bankedreg bankedreg
     * }
     */
    public static final long bankedreg$offset() {
        return bankedreg$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * arm_bankedreg bankedreg
     * }
     */
    public static int bankedreg(MemorySegment union) {
        return union.get(bankedreg$LAYOUT, bankedreg$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * arm_bankedreg bankedreg
     * }
     */
    public static void bankedreg(MemorySegment union, int fieldValue) {
        union.set(bankedreg$LAYOUT, bankedreg$OFFSET, fieldValue);
    }

    private static final OfInt raw_val$LAYOUT = (OfInt)$LAYOUT.select(groupElement("raw_val"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static final OfInt raw_val$layout() {
        return raw_val$LAYOUT;
    }

    private static final long raw_val$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static final long raw_val$offset() {
        return raw_val$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static int raw_val(MemorySegment union) {
        return union.get(raw_val$LAYOUT, raw_val$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * int raw_val
     * }
     */
    public static void raw_val(MemorySegment union, int fieldValue) {
        union.set(raw_val$LAYOUT, raw_val$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this union
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

