// Generated by jextract

package com.suko.capstone4j.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef int (*cs_vsnprintf_t)(char *, size_t, const char *, va_list) __attribute__((cdecl))
 * }
 */
public class cs_vsnprintf_t {

    cs_vsnprintf_t() {
        // Should not be called directly
    }

    /**
     * The function pointer signature, expressed as a functional interface
     */
    public interface Function {
        int apply(MemorySegment str, long size, MemorySegment format, MemorySegment ap);
    }

    private static final FunctionDescriptor $DESC = FunctionDescriptor.of(
        capstone_h.C_INT,
        capstone_h.C_POINTER,
        capstone_h.C_LONG_LONG,
        capstone_h.C_POINTER,
        capstone_h.C_POINTER
    );

    /**
     * The descriptor of this function pointer
     */
    public static FunctionDescriptor descriptor() {
        return $DESC;
    }

    private static final MethodHandle UP$MH = capstone_h.upcallHandle(cs_vsnprintf_t.Function.class, "apply", $DESC);

    /**
     * Allocates a new upcall stub, whose implementation is defined by {@code fi}.
     * The lifetime of the returned segment is managed by {@code arena}
     */
    public static MemorySegment allocate(cs_vsnprintf_t.Function fi, Arena arena) {
        return Linker.nativeLinker().upcallStub(UP$MH.bindTo(fi), $DESC, arena);
    }

    private static final MethodHandle DOWN$MH = Linker.nativeLinker().downcallHandle($DESC);

    /**
     * Invoke the upcall stub {@code funcPtr}, with given parameters
     */
    public static int invoke(MemorySegment funcPtr,MemorySegment str, long size, MemorySegment format, MemorySegment ap) {
        try {
            return (int) DOWN$MH.invokeExact(funcPtr, str, size, format, ap);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }
}

