// Generated by jextract

package com.suko.capstone4j.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * typedef struct cs_xtensa_operand {
 *     uint8_t type;
 *     uint8_t access;
 *     union {
 *         uint8_t reg;
 *         int32_t imm;
 *         cs_xtensa_op_mem mem;
 *     };
 * } cs_xtensa_op
 * }
 */
public class cs_xtensa_op extends cs_xtensa_operand {

    cs_xtensa_op() {
        // Should not be called directly
    }
}

