// Generated by jextract

package com.suko.capstone4j.internal;

import java.lang.invoke.*;
import java.lang.foreign.*;
import java.nio.ByteOrder;
import java.util.*;
import java.util.function.*;
import java.util.stream.*;

import static java.lang.foreign.ValueLayout.*;
import static java.lang.foreign.MemoryLayout.PathElement.*;

/**
 * {@snippet lang=c :
 * struct hppa_modifier {
 *     hppa_modifier_type type;
 *     union {
 *         char str_mod[8];
 *         uint32_t int_mod;
 *     };
 * }
 * }
 */
public class hppa_modifier {

    hppa_modifier() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        capstone_h.C_INT.withName("type"),
        MemoryLayout.unionLayout(
            MemoryLayout.sequenceLayout(8, capstone_h.C_CHAR).withName("str_mod"),
            capstone_h.C_INT.withName("int_mod")
        ).withName("$anon$505:2")
    ).withName("hppa_modifier");

    /**
     * The layout of this struct
     */
    public static final GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfInt type$LAYOUT = (OfInt)$LAYOUT.select(groupElement("type"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * hppa_modifier_type type
     * }
     */
    public static final OfInt type$layout() {
        return type$LAYOUT;
    }

    private static final long type$OFFSET = 0;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * hppa_modifier_type type
     * }
     */
    public static final long type$offset() {
        return type$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * hppa_modifier_type type
     * }
     */
    public static int type(MemorySegment struct) {
        return struct.get(type$LAYOUT, type$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * hppa_modifier_type type
     * }
     */
    public static void type(MemorySegment struct, int fieldValue) {
        struct.set(type$LAYOUT, type$OFFSET, fieldValue);
    }

    private static final SequenceLayout str_mod$LAYOUT = (SequenceLayout)$LAYOUT.select(groupElement("$anon$505:2"), groupElement("str_mod"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static final SequenceLayout str_mod$layout() {
        return str_mod$LAYOUT;
    }

    private static final long str_mod$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static final long str_mod$offset() {
        return str_mod$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static MemorySegment str_mod(MemorySegment struct) {
        return struct.asSlice(str_mod$OFFSET, str_mod$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static void str_mod(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, str_mod$OFFSET, str_mod$LAYOUT.byteSize());
    }

    private static long[] str_mod$DIMS = { 8 };

    /**
     * Dimensions for array field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static long[] str_mod$dimensions() {
        return str_mod$DIMS;
    }
    private static final VarHandle str_mod$ELEM_HANDLE = str_mod$LAYOUT.varHandle(sequenceElement());

    /**
     * Indexed getter for field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static byte str_mod(MemorySegment struct, long index0) {
        return (byte)str_mod$ELEM_HANDLE.get(struct, 0L, index0);
    }

    /**
     * Indexed setter for field:
     * {@snippet lang=c :
     * char str_mod[8]
     * }
     */
    public static void str_mod(MemorySegment struct, long index0, byte fieldValue) {
        str_mod$ELEM_HANDLE.set(struct, 0L, index0, fieldValue);
    }

    private static final OfInt int_mod$LAYOUT = (OfInt)$LAYOUT.select(groupElement("$anon$505:2"), groupElement("int_mod"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * uint32_t int_mod
     * }
     */
    public static final OfInt int_mod$layout() {
        return int_mod$LAYOUT;
    }

    private static final long int_mod$OFFSET = 4;

    /**
     * Offset for field:
     * {@snippet lang=c :
     * uint32_t int_mod
     * }
     */
    public static final long int_mod$offset() {
        return int_mod$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * uint32_t int_mod
     * }
     */
    public static int int_mod(MemorySegment struct) {
        return struct.get(int_mod$LAYOUT, int_mod$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * uint32_t int_mod
     * }
     */
    public static void int_mod(MemorySegment struct, int fieldValue) {
        struct.set(int_mod$LAYOUT, int_mod$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

